### ISSUE TITLE
IP150+

### ISSUE THREAD

**Issue by brunoshine** [maisken/Paradox_IP150#22]
Hi all,

im going to purchase a paradox alarm system, and I was wondering if this package has been tested with the IP150+ model?

thanks
Bruno

**Comment by ukrolelo** [comment]
+1

**Comment by yukeiw** [comment]
+1

**Comment by alfredopironti** [comment]
I haven't tested it with IP150+, but I'd guess it would mostly depend on the firmware. If it uses a relatively recent firmware version, I'm afraid it's unlikely to work with this package. I'd be happy to hear about more user reports.

**Comment by alekth** [comment]
Can confirm that IP150+ does not work for me, at least with its currently installed version 5.02.019.
It does return the correct error on wrong credentials (provided on purpose to test), but with the right ones it fails to connect with:

Traceback (most recent call last):
  File "//ip150_mqtt.py", line 140, in <module>
    ip_mqtt.loop_forever()
  File "//ip150_mqtt.py", line 131, in loop_forever
    mqc.connect(mqtt_hostname, mqtt_port)
  File "/usr/lib/python3.9/site-packages/paho/mqtt/client.py", line 914, in connect
    return self.reconnect()
  File "/usr/lib/python3.9/site-packages/paho/mqtt/client.py", line 1044, in reconnect
    sock = self._create_socket_connection()
  File "/usr/lib/python3.9/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
  File "/usr/lib/python3.9/socket.py", line 844, in create_connection
    raise err
  File "/usr/lib/python3.9/socket.py", line 832, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
