### ISSUE TITLE
malfunction after massive re-config

### ISSUE THREAD

**Issue by hoebanx** [maisken/Paradox_IP150#28]
Hello,

I was really happy with the add-on for now 2 years. I have a lot of automation based on movment detection.
Unfortunately I had to change my Internet router / docker / IP ranges.
I re-used my HA backup, reinstalled it and changed the IPs
Surprizely my mqtt user disappered. I recreated him with the same name/psw. At the end, it doens't work
please find bellow the logs

When I try to connect on my IP150, he says that someone is already conected. So it seems to work. But the data aren't available in HA.

Thanks a lot for your help
Ludovic

I'm working with 
HA core 2022.2.3 (latest)
Paradox IP50 MQTT adapter 1.1
Mosquitto broquer 6.0.1

Mosquitto broker
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] mosquitto.sh: executing... 
[09:52:46] INFO: Setting up user mqtt
[09:52:47] INFO: Certificates found: SSL is available
[cont-init.d] mosquitto.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[09:52:48] INFO: Starting NGINX for authentication handling...
[09:52:49] INFO: Starting mosquitto MQTT broker...
1644310369: mosquitto version 1.6.12 starting
1644310369: |-- *** auth-plug: startup
[09:52:52] INFO: Successfully send discovery information to Home Assistant.
[09:52:52] INFO: Successfully send service information to the Supervisor.
1644310369: Config loaded from /etc/mosquitto/mosquitto.conf.
1644310369: Loading plugin: /usr/share/mosquitto/auth-plug.so
1644310369:  ├── Username/password checking enabled.
1644310369:  ├── TLS-PSK checking enabled.
1644310369:  └── Extended authentication not enabled.
1644310369: Opening ipv4 listen socket on port 1883.
1644310369: Opening ipv6 listen socket on port 1883.
1644310369: Opening websockets listen socket on port 1884.
1644310369: Opening ipv4 listen socket on port 8883.
1644310369: Opening ipv6 listen socket on port 8883.
1644310369: Opening websockets listen socket on port 8884.
1644310370: Warning: Mosquitto should not be run as root/administrator.
1644310370: mosquitto version 1.6.12 running
1644310370: New connection from 127.0.0.1 on port 1883.
1644310370: Socket error on client <unknown>, disconnecting.
1644310377: New connection from 172.30.32.1 on port 1883.

Paradox IP150 MQTT Adapter
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Traceback (most recent call last):
  File "ip150_mqtt.py", line 140, in <module>
    ip_mqtt.loop_forever()
  File "ip150_mqtt.py", line 122, in loop_forever
    self.ip.login(self._cfg['PANEL_CODE'], self._cfg['PANEL_PASSWORD'])
  File "/ip150.py", line 142, in login
    raise Paradox_IP150_Error(
ip150.Paradox_IP150_Error: Wrong page fetcehd. Did you connect to the right server and port? Server returned: <!DOCTYPE HTML PUBLIC '-//W3C//DTD HTML 4.01 Transitional//EN' 'http://www.w3.org/TR/html4/loose.dtd'>
<html>
<head>
	<meta http-equiv='content-type' content='text/html; charset=UTF-8' />
	<link rel='stylesheet' type='text/css' href='webstyles.css' />
	<script type='text/javascript' src='langue.js'></script><script type='text/javascript' src='commun.js'></script></head><body><div id = 'ERROR' style='margin-top:60px;'></div><title>Your Paradox System</title><script type='text/javascript'>;var sre = "<table><tr><td align='middle'><div class='box' style='width:460px;margin:80px;'><div class='box-title strips'>" + top.ln_cant[1] + "</div><div class='box-content'><div class='msg' id='MESSAGE'></div></div></div></td></tr></table>";document.getElementById('ERROR').innerHTML = sre; document.getElementById('MESSAGE').innerHTML = top.cant('LUDO');</script></body></html>
![2022-02-08 09_55_35-Window](https://user-images.githubusercontent.com/77239440/152952645-51b3fe15-ef82-4ec4-9842-5ebefbddee74.png)
![2022-02-08 09_56_47-Window](https://user-images.githubusercontent.com/77239440/152952649-c367258a-95d7-487e-b5f7-30d66ba1f25a.png)
![2022-02-08 09_57_26-Window](https://user-images.githubusercontent.com/77239440/152952653-d1cd87ad-e232-4e4c-bb1b-59a7cf1b510f.png)

**Comment by hoebanx** [comment]
Ok, problem solved.
Mqtt mosquito, ip150 and "config>device/services/configuration.yalm(mqtt)" had to be updated
