### ISSUE TITLE
PAI.paradox.hardware.panel Unable to parse RAM Status Block (0)

### ISSUE THREAD

**Issue by brettrussellza** [maisken/Paradox_IP150#31]
Hi, 

Getting a strange error here. Here are my logs:

`2022-04-24 14:29:30,129 - INFO     - PAI - Starting Paradox Alarm Interface 3.0.1
2022-04-24 14:29:30,130 - INFO     - PAI - Config loaded from /data/options.json
2022-04-24 14:29:30,131 - INFO     - PAI - Console Log level set to 20
2022-04-24 14:29:30,168 - INFO     - PAI.paradox.interfaces - Starting BasicMQTTInterface Interface
2022-04-24 14:29:30,170 - INFO     - PAI.paradox.interfaces.mqtt.core - MQTT loop started
2022-04-24 14:29:30,174 - INFO     - PAI.paradox.interfaces - Starting HomeAssistantMQTTInterface Interface
2022-04-24 14:29:30,175 - INFO     - PAI - Starting...
2022-04-24 14:29:30,176 - INFO     - PAI.paradox.paradox - Connecting to interface
2022-04-24 14:29:30,176 - INFO     - PAI.paradox.paradox - Using IP Connection
2022-04-24 14:29:30,266 - INFO     - PAI.paradox.connections.ip.connection - Connecting. Try 1/3
2022-04-24 14:29:30,269 - INFO     - PAI.paradox.connections.connection - Connection established
2022-04-24 14:29:30,270 - INFO     - PAI.paradox.connections.ip.commands - Authenticating with IP Module
2022-04-24 14:29:30,274 - INFO     - PAI.paradox.connections.ip.commands - Authentication Success. IP(IP150) Module version 20, firmware: 5.2, serial: 71035098
2022-04-24 14:29:30,285 - INFO     - PAI.paradox.connections.ip.commands - Session successfully established with IP Module
2022-04-24 14:29:30,286 - INFO     - PAI.paradox.paradox - Connecting to Panel
2022-04-24 14:29:30,379 - INFO     - PAI.paradox.paradox - Panel Identified MG5050  version 7.21 build 0
2022-04-24 14:29:30,380 - INFO     - PAI.paradox.paradox - Initiating panel connection
2022-04-24 14:29:30,478 - INFO     - PAI.paradox.hardware.spectra_magellan.panel - Installer login
2022-04-24 14:29:30,593 - INFO     - PAI.paradox.hardware.spectra_magellan.panel - Authentication Success
2022-04-24 14:29:30,594 - INFO     - PAI.paradox.paradox - Connection OK
2022-04-24 14:29:30,595 - INFO     - PAI.paradox.paradox - Loading data from panel memory
2022-04-24 14:29:30,595 - INFO     - PAI.paradox.hardware.panel - Loading definitions
2022-04-24 14:29:30,595 - INFO     - PAI.paradox.hardware.panel - Updating Definitions from Panel
2022-04-24 14:29:30,972 - INFO     - PAI.paradox.hardware.panel - Zone definitions loaded (0.38s)
2022-04-24 14:29:31,176 - INFO     - PAI.paradox.interfaces.mqtt.core - MQTT Broker Connected
2022-04-24 14:29:31,335 - INFO     - PAI.paradox.hardware.panel - Pgm definitions loaded (0.36s)
2022-04-24 14:29:31,338 - INFO     - PAI.paradox.hardware.panel - Loading labels
2022-04-24 14:29:31,338 - INFO     - PAI.paradox.hardware.panel - Updating Labels from Panel
2022-04-24 14:29:31,700 - INFO     - PAI.paradox.hardware.panel - Zone labels loaded (0.36s): Entrance Door, Mainbed Pir, Passage Pir, Lounge Pir, Playrooom Pir, Study Pir and Dr, Lounge Door, Kitchen Door
2022-04-24 14:29:31,884 - INFO     - PAI.paradox.hardware.panel - Pgm labels loaded (0.18s): Panic Radio, Burglary Radio, Status LED, Open/Close Radio
2022-04-24 14:29:31,976 - INFO     - PAI.paradox.hardware.panel - Partition labels loaded (0.09s): Area 1, Area 2
2022-04-24 14:29:32,431 - INFO     - PAI.paradox.hardware.panel - User labels loaded (0.45s): System Master (B, Farhana, Home Assistant, User 04, User 05, User 06, User 07, User 08, User 09, User 10
2022-04-24 14:29:32,432 - INFO     - PAI.paradox.hardware.panel - Module labels loaded (0.0s): 
2022-04-24 14:29:32,432 - INFO     - PAI.paradox.hardware.panel - Repeater labels loaded (0.0s): 
2022-04-24 14:29:32,433 - INFO     - PAI.paradox.hardware.panel - Keypad labels loaded (0.0s): 
2022-04-24 14:29:32,529 - INFO     - PAI.paradox.hardware.panel - Site labels loaded (0.1s): Your Alarm Site
2022-04-24 14:29:32,741 - INFO     - PAI.paradox.hardware.panel - Siren labels loaded (0.21s): Wireless Siren 1, Wireless Siren 2, Wireless Siren 3
2022-04-24 14:29:32,742 - INFO     - PAI.paradox.paradox - Running
2022-04-24 14:29:32,831 - ERROR    - PAI.paradox.hardware.panel - Unable to parse RAM Status Block (0)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/paradox/hardware/panel.py", line 338, in handle_status
    res = parser.parse(mvars.data)
  File "/usr/local/lib/python3.9/site-packages/construct/core.py", line 308, in parse
    return self.parse_stream(io.BytesIO(data), **contextkw)
  File "/usr/local/lib/python3.9/site-packages/construct/core.py", line 320, in parse_stream
    return self._parsereport(stream, context, "(parsing)")
  File "/usr/local/lib/python3.9/site-packages/construct/core.py", line 332, in _parsereport
    obj = self._parse(stream, context, path)
  File "/usr/local/lib/python3.9/site-packages/construct/core.py", line 2000, in _parse
    subobj = sc._parsereport(stream, context, path)
  File "/usr/local/lib/python3.9/site-packages/construct/core.py", line 332, in _parsereport
    obj = self._parse(stream, context, path)
  File "/usr/local/lib/python3.9/site-packages/construct/core.py", line 2489, in _parse
    return self.subcon._parsereport(stream, context, path)
  File "/usr/local/lib/python3.9/site-packages/construct/core.py", line 332, in _parsereport
    obj = self._parse(stream, context, path)
  File "/usr/local/lib/python3.9/site-packages/construct/core.py", line 2000, in _parse
    subobj = sc._parsereport(stream, context, path)
  File "/usr/local/lib/python3.9/site-packages/construct/core.py", line 332, in _parsereport
    obj = self._parse(stream, context, path)
  File "/usr/local/lib/python3.9/site-packages/construct/core.py", line 2489, in _parse
    return self.subcon._parsereport(stream, context, path)
  File "/usr/local/lib/python3.9/site-packages/construct/core.py", line 332, in _parsereport
    obj = self._parse(stream, context, path)
  File "/usr/local/lib/python3.9/site-packages/construct/core.py", line 2000, in _parse
    subobj = sc._parsereport(stream, context, path)
  File "/usr/local/lib/python3.9/site-packages/construct/core.py", line 332, in _parsereport
    obj = self._parse(stream, context, path)
  File "/usr/local/lib/python3.9/site-packages/construct/core.py", line 2489, in _parse
    return self.subcon._parsereport(stream, context, path)
  File "/usr/local/lib/python3.9/site-packages/construct/core.py", line 332, in _parsereport
    obj = self._parse(stream, context, path)
  File "/usr/local/lib/python3.9/site-packages/construct/core.py", line 719, in _parse
    return self._decode(obj, context, path)
  File "/usr/local/lib/python3.9/site-packages/paradox/hardware/spectra_magellan/adapters.py", line 10, in _decode
    return datetime.datetime(obj[0] * 100 + obj[1], obj[2], obj[3], obj[4], obj[5])
ValueError: month must be in 1..12
2022-04-24 14:29:33,379 - ERROR    - PAI.paradox.paradox - Loop
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/paradox/paradox.py", line 278, in loop
    merged = deep_merge(*result, extend_lists=True, initializer={})
  File "/usr/local/lib/python3.9/site-packages/paradox/lib/utils.py", line 80, in deep_merge
    return functools.reduce(merge_into, dicts, initializer)
  File "/usr/local/lib/python3.9/site-packages/paradox/lib/utils.py", line 69, in merge_into
    for key in d2:
TypeError: 'NoneType' object is not iterable
2022-04-24 14:29:33,471 - ERROR    - PAI.paradox.hardware.panel - Unable to parse RAM Status Block (0)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/paradox/hardware/panel.py", line 338, in handle_status
    res = parser.parse(mvars.data)
  File "/usr/local/lib/python3.9/site-packages/construct/core.py", line 308, in parse
    return self.parse_stream(io.BytesIO(data), **contextkw)
  File "/usr/local/lib/python3.9/site-packages/construct/core.py", line 320, in parse_stream
    return self._parsereport(stream, context, "(parsing)")
  File "/usr/local/lib/python3.9/site-packages/construct/core.py", line 332, in _parsereport
    obj = self._parse(stream, context, path)
  File "/usr/local/lib/python3.9/site-packages/construct/core.py", line 2000, in _parse
    subobj = sc._parsereport(stream, context, path)
  File "/usr/local/lib/python3.9/site-packages/construct/core.py", line 332, in _parsereport
    obj = self._parse(stream, context, path)
  File "/usr/local/lib/python3.9/site-packages/construct/core.py", line 2489, in _parse
    return self.subcon._parsereport(stream, context, path)
  File "/usr/local/lib/python3.9/site-packages/construct/core.py", line 332, in _parsereport
    obj = self._parse(stream, context, path)
  File "/usr/local/lib/python3.9/site-packages/construct/core.py", line 2000, in _parse
    subobj = sc._parsereport(stream, context, path)
  File "/usr/local/lib/python3.9/site-packages/construct/core.py", line 332, in _parsereport
    obj = self._parse(stream, context, path)
  File "/usr/local/lib/python3.9/site-packages/construct/core.py", line 2489, in _parse
    return self.subcon._parsereport(stream, context, path)
  File "/usr/local/lib/python3.9/site-packages/construct/core.py", line 332, in _parsereport
    obj = self._parse(stream, context, path)
  File "/usr/local/lib/python3.9/site-packages/construct/core.py", line 2000, in _parse
    subobj = sc._parsereport(stream, context, path)
  File "/usr/local/lib/python3.9/site-packages/construct/core.py", line 332, in _parsereport
    obj = self._parse(stream, context, path)
  File "/usr/local/lib/python3.9/site-packages/construct/core.py", line 2489, in _parse
    return self.subcon._parsereport(stream, context, path)
  File "/usr/local/lib/python3.9/site-packages/construct/core.py", line 332, in _parsereport
    obj = self._parse(stream, context, path)
  File "/usr/local/lib/python3.9/site-packages/construct/core.py", line 719, in _parse
    return self._decode(obj, context, path)
  File "/usr/local/lib/python3.9/site-packages/paradox/hardware/spectra_magellan/adapters.py", line 10, in _decode
    return datetime.datetime(obj[0] * 100 + obj[1], obj[2], obj[3], obj[4], obj[5])
ValueError: month must be in 1..12
2022-04-24 14:29:34,017 - ERROR    - PAI.paradox.paradox - Loop
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/paradox/paradox.py", line 278, in loop
    merged = deep_merge(*result, extend_lists=True, initializer={})
  File "/usr/local/lib/python3.9/site-packages/paradox/lib/utils.py", line 80, in deep_merge
    return functools.reduce(merge_into, dicts, initializer)
  File "/usr/local/lib/python3.9/site-packages/paradox/lib/utils.py", line 69, in merge_into
    for key in d2:
TypeError: 'NoneType' object is not iterable`

Here is my config:

`LOGGING_LEVEL_CONSOLE: 20
LOGGING_LEVEL_FILE: 40
CONNECTION_TYPE: IP
SERIAL_PORT: /dev/ttyUSB0
SERIAL_BAUD: 9600
IP_CONNECTION_HOST: 192.168.******
IP_CONNECTION_PORT: 10000
IP_CONNECTION_PASSWORD: ******
KEEP_ALIVE_INTERVAL: 10
LIMITS:
  zone: auto
  user: 1-10
  door: ''
  pgm: 1-5
  partition: auto
  module: ''
  repeater: ''
  keypad: ''
  key-switch: ''
SYNC_TIME: true
SYNC_TIME_MIN_DRIFT: 120
PASSWORD: '********'
MQTT_ENABLE: true
MQTT_HOST: 192.168.********
MQTT_PORT: 1883
MQTT_KEEPALIVE: 60
MQTT_USERNAME: ********
MQTT_PASSWORD: *********
MQTT_HOMEASSISTANT_AUTODISCOVERY_ENABLE: true
COMMAND_ALIAS:
  arm: partition all arm
  disarm: partition all disarm
MQTT_COMMAND_ALIAS:
  armed_home: arm_stay
  armed_night: arm_sleep
  armed_away: arm
  disarmed: disarm
HOMEASSISTANT_NOTIFICATIONS_EVENT_FILTERS:
  - live,alarm,-restore
  - live,trouble,-clock
  - live,tamper
HOMEASSISTANT_PUBLISH_PARTITION_PROPERTIES:
  - target_state
  - current_state
HOMEASSISTANT_PUBLISH_ZONE_PROPERTIES:
  - open
  - tamper
PUSHBULLET_CONTACTS: []
PUSHBULLET_EVENT_FILTERS:
  - live,alarm,-restore
  - live,trouble,-clock
  - live,tamper
PUSHOVER_EVENT_FILTERS:
  - live,alarm,-restore
  - live,trouble,-clock
  - live,tamper
PUSHOVER_BROADCAST_KEYS: []
SIGNAL_CONTACTS: []
SIGNAL_EVENT_FILTERS:
  - live,alarm,-restore
  - live,trouble,-clock
  - live,tamper
GSM_CONTACTS: []
GSM_EVENT_FILTERS:
  - live,alarm,-restore
  - live,trouble,-clock
  - live,tamper
IP_INTERFACE_ENABLE: false
IP_INTERFACE_PASSWORD: *******
DUMMY_EVENT_FILTERS: []
`

Any assistance would be appreciated.

**Comment by brettrussellza** [comment]
Another error:

`2022-04-24 14:32:33,668 - ERROR    - PAI.paradox.hardware.spectra_magellan.panel - Exception parsing message: b'e207700001142e01030000000000005061737361676500506972000000000000000000008f'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/paradox/hardware/spectra_magellan/panel.py", line 173, in parse_message
    return parsers.LiveEvent.parse(message)
  File "/usr/local/lib/python3.9/site-packages/construct/core.py", line 308, in parse
    return self.parse_stream(io.BytesIO(data), **contextkw)
  File "/usr/local/lib/python3.9/site-packages/construct/core.py", line 320, in parse_stream
    return self._parsereport(stream, context, "(parsing)")
  File "/usr/local/lib/python3.9/site-packages/construct/core.py", line 332, in _parsereport
    obj = self._parse(stream, context, path)
  File "/usr/local/lib/python3.9/site-packages/construct/core.py", line 2000, in _parse
    subobj = sc._parsereport(stream, context, path)
  File "/usr/local/lib/python3.9/site-packages/construct/core.py", line 332, in _parsereport
    obj = self._parse(stream, context, path)
  File "/usr/local/lib/python3.9/site-packages/construct/core.py", line 2489, in _parse
    return self.subcon._parsereport(stream, context, path)
  File "/usr/local/lib/python3.9/site-packages/construct/core.py", line 332, in _parsereport
    obj = self._parse(stream, context, path)
  File "/usr/local/lib/python3.9/site-packages/construct/core.py", line 4368, in _parse
    obj = self.subcon._parsereport(stream, context, path)
  File "/usr/local/lib/python3.9/site-packages/construct/core.py", line 332, in _parsereport
    obj = self._parse(stream, context, path)
  File "/usr/local/lib/python3.9/site-packages/construct/core.py", line 2000, in _parse
    subobj = sc._parsereport(stream, context, path)
  File "/usr/local/lib/python3.9/site-packages/construct/core.py", line 332, in _parsereport
    obj = self._parse(stream, context, path)
  File "/usr/local/lib/python3.9/site-packages/construct/core.py", line 2489, in _parse
    return self.subcon._parsereport(stream, context, path)
  File "/usr/local/lib/python3.9/site-packages/construct/core.py", line 332, in _parsereport
    obj = self._parse(stream, context, path)
  File "/usr/local/lib/python3.9/site-packages/construct/core.py", line 719, in _parse
    return self._decode(obj, context, path)
  File "/usr/local/lib/python3.9/site-packages/paradox/hardware/spectra_magellan/adapters.py", line 10, in _decode
    return datetime.datetime(obj[0] * 100 + obj[1], obj[2], obj[3], obj[4], obj[5])
ValueError: month must be in 1..12`

Clearly it's communicating, but not able to parse the data??

**Comment by XeSSiV** [comment]
If you are still having issues, try setting this line as below:
MQTT_HOST: 'mqtt://192.168.x.x'
or
MQTT_HOST: 'mqtt://core-mosquitto'
if you're using localhost as MQTT broker
